---
- name: Load vault secrets
  include_vars:
    file: vault.yml

- name: Setup files and certificates
  include_tasks: setup_files.yml

- name: Deploy stack
  include_tasks: deploy.yml

- name: Configure GLPI
  include_tasks: configure.yml

- name: Show access URL
  debug:
    msg: "https://{{ manager_ip }}"
  run_once: true
