all:
  children:
    managers:
      hosts:
        swarm-manager:
          ansible_connection: lxd
          ansible_host: swarm-manager
    workers:
      hosts:
        swarm-worker1:
          ansible_connection: lxd
          ansible_host: swarm-worker1
        swarm-worker2:
          ansible_connection: lxd
          ansible_host: swarm-worker2
