---
- name: Bootstrap Containers
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Docker and Swarm
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy GLPI Stack
  hosts: managers
  become: yes
  roles:
    - glpi
